### ISSUE TITLE
CRAN submission reply

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rdataretriever#100]
> [This was generated from CRAN.R-project.org/submit.html]
>
> The following package was uploaded to CRAN:
> ===========================================
>
> Package Information:
> Package: rdataretriever
> Version: 1.0.0
> Title: R Interface to the Data Retriever
> Author(s): Daniel McGlinn [aut, cre], Henry Senyondo [aut], Shawn Taylor
>   [aut], Ethan White [aut]
> Maintainer: Daniel McGlinn <danmcglinn@gmail.com>
> Depends: R (>= 3.0.0)
> Description: Provides an R interface to the Data Retriever
>   (http://data-retriever.org/) v

Thanks, please enclose the URL in <> rather than () (for auto-linking).

ia the Data Retriever's command
>   line interface. The Data Retriever automates the tasks of
>   finding, downloading, and cleaning public datasets, and then
>   stores them in a local database.
> License: MIT + file LICENSE
> Imports: utils
>
>
> The maintainer confirms that he or she
> has read and agrees to the CRAN policies.
>
> Submitter's comment: This package is replacing the package on CRAN called
>   ecoretriever which we would like to have archived.

Why can't you simply update ecoretriever? Typically we do not allow for 
renaming packages without very good reasons.

We also see:

Found the following (possibly) invalid URLs:
  URL: http://cran.rstudio.com/web/packages/rdataretriever/index.html 
(moved to https://cran.rstudio.com/web/packages/rdataretriever/index.html)
    From: README.md
    Status: 404
    Message: Not Found
    CRAN URL not in canonical form
  Canonical CRAN.R-project.org URLs use https.

Please fix and resubmit preferrably as 'ecoretriever'.

Best,
Uwe Ligges

> =================================================
>
> Original content of DESCRIPTION file:
>
> Package: rdataretriever
> Title: R Interface to the Data Retriever
> Description: Provides an R interface to the Data Retriever
>     (http://data-retriever.org/) via the Data Retriever's
>     command line interface. The Data Retriever automates the
>     tasks of finding, downloading, and cleaning public datasets,
>     and then stores them in a local database.
> Version: 1.0.0
> Date: 2017-02-21
> Authors@R: c(person("Daniel", "McGlinn", role = c("aut", "cre"),
>     email = "danmcglinn@gmail.com"),
>     person("Henry", "Senyondo", role = "aut",
>     email = "henrykironde@gmail.com"),
>     person("Shawn", "Taylor", role = "aut",
>     email = "shawntaylor@weecology.org"),
>     person("Ethan", "White", role = "aut",
>     email = "ethan@weecology.org"))
> BugReports: https://github.com/ropensci/rdataretriever/issues
> URL: https://github.com/ropensci/rdataretriever/
> Depends: R (>= 3.0.0)
> Imports: utils
> SystemRequirements: Data Retriever (>= 1.8)
> License: MIT + file LICENSE
> LazyData: true
> RoxygenNote: 5.0.1
> NeedsCompilation: no
> Packaged: 2017-02-21 16:46:44 UTC; danmcglinn
> Author: Daniel McGlinn [aut, cre],
>   Henry Senyondo [aut],
>   Shawn Taylor [aut],
>   Ethan White [aut]
> Maintainer: Daniel McGlinn <danmcglinn@gmail.com>
>

**Comment by dmcglinn** [comment]
So the question is should we try to fight the name change or not. We could also decide to just distribute the package through github only.

**Comment by ethanwhite** [comment]
Yes, we should fight for the name change. I'd suggest that we make all of the other fixes and resubmit as `rdataretriever` with a detailed explanation of why the old name doesn't make sense at this point. I'm willing to draft that language if you'd like.

**Comment by ethanwhite** [comment]
Just to follow. I think we have "very good reasons" here, so there's no reason not to make those arguments. Strategically if we send back a perfect package with a good explanation of the name change then it should be easier to say yes than no.

**Comment by dmcglinn** [comment]
Sounds good. Can you please post here a draft of the rationale. Thanks

**Comment by ethanwhite** [comment]
> Why can't you simply update ecoretriever? Typically we do not allow for
renaming packages without very good reasons.

This packages is a wrapper for software written in Python that used to be called the EcoData Retriever. That software used to focus on ecological data, but has recently been updated to work with data much more broadly. As a result the Python software has been renamed the Data Retriever and it includes lots of data packages that are not related in any way to the "eco" in the current name. This expansion and associated renaming is related to funding that helps cover the development of both the Python and the R packages. It would be confusing to not indicate this change in focus and naming in the R package. That said, we understand that renaming could be technically problematic and we are happy to handle this in whatever way is easiest and most appropriate for CRAN. If it is better to archive the existing `ecoretriever` package and submit as a new package named `rdataretriever` we are happy to do that.

**Comment by ethanwhite** [comment]
Now on CRAN!! https://cran.r-project.org/package=rdataretriever
