### ISSUE TITLE
dataset names

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rdataretriever#112]
We currently convert "-" to "_" see: 

https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L117

But maybe we should just keep the dataset names consistent with what is returned by `rdataretriever::datasets` which seem to have converged on all names that separate words by "-". @ethanwhite any thoughts here? Also do you think that the dataset names have stabilized for the most part?

**Comment by ethanwhite** [comment]
Yeah, I agree. They are stable, that was a one time change for the move to 2.0.

**Comment by dmcglinn** [comment]
the one argument for keeping the "_" rather than "-" that I can see is that R tries to treat "-" like a minus sign when referencing element names using "$". For example, `vegdata$plant-ok-comp` returns and error that the object `ok` and `comp` are not defined. This can be solved by using `vegdata$'plant-ok-comp'` which is just a little clunkier.

**Comment by ethanwhite** [comment]
That's a good point. Something similar in Python is why the file names are `_` and the names are `-`. It's a juggle between programming language conventions (more `_`) and package manager conventions (more `-`). I'm happy either way.

**Comment by dmcglinn** [comment]
Thanks for the feedback, I'll hold off on changing our code then (= "-" still converted to "_")
