### ISSUE TITLE
What to do if dataset name is mispecified

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rdataretriever#113]
Currently if a user tries to install a dataset that is not listed by `rdataretriever::datasets` no error is issued. In fact when using `fetch` an empty list is even returned. I propose we add at `stop('Dataset not supported, see available list of data given by datasets()')`

**Comment by ethanwhite** [comment]
Agreed. We should be handling that better in the core retriever and it should get taken care of this summer as part of our implementation of a formal Python interface, but I see no reason not to go ahead and fix it directly in the R package for now.

**Comment by pranita-s** [comment]
Among three functions - download and install display following message:
`The dataset dataset_name isn't currently available in the Retriever
Run 'retriever ls to see a list of currently available datasets`.

Only fetch does not, as line 121 has "-q" option. If it is removed, it will display the message too. Also the length of "bone" variable can be checked before returning. If it is 0, it implies the dataset is not available and it need not be returned. Only the message of unavailability can be shown.

**Comment by ethanwhite** [comment]
I like the empty list with the warning, which is what @pranita-s has implemented in #134. I'm going to review that shortly.

@dmcglinn - does that seem like a reasonable solution to you?

**Comment by ethanwhite** [comment]
Hmmm, OK this isn't actually totally satisfactory since the recommend fix applies to the CLI not the the R interface. I think we should catch these and return R specific advice about checking `datasets` and updating.

**Comment by ethanwhite** [comment]
This was fixed in #134. Thanks again @pranita-s!
