### ISSUE TITLE
Anaconda installation fails to connect path

### ISSUE THREAD

**Issue by DAPPERstats** [ropensci/rdataretriever#121]
If you use install method 1 with Anaconda (as suggested on the site when you don't have Python installed already), the installation does not set the path fully and is not available in R.

**Comment by ethanwhite** [comment]
Is this issue just in RStudio or does it also happen in base R?

**Comment by DAPPERstats** [comment]
I actually only know that it wasn't available in base R. I'm not sure re: RStudio.

**Comment by ethanwhite** [comment]
Thanks (there are some issues in RStudio that aren't a problem in base, so the fact that it's in base is all we need to know). A couple of additional questions:

1. Does the CLI work properly?
2. What does `which retriever` return from the shell?

**Comment by DAPPERstats** [comment]
Got it. 
The CLI works fine.
As @henrykironde and I found out earlier today, "which" doesn't work in Anaconda. I can call up the help and info on the install, though, and it's v2.1.0

**Comment by DAPPERstats** [comment]
Also, I should note that an independent install via method 2 (the executable file) works and links with R just fine. 
Thanks!

**Comment by ethanwhite** [comment]
OK, thanks.

I'm not sure what you mean by '"which" doesn't work in Anaconda'. `which` is a shell command that tells you where a program on the path is located. It won't work from `cmd` in Windows. I think that `WHERE` should do the equivalent thing for Windows, so at the command prompt try running:

```
WHERE retriever
```

and let us know what it returns.

What appears to be going on is that R isn't handling the Windows path properly for some reason. Since the CLI works fine the retriever is on the path, but R isn't finding it. We've run into this issue before and have a bunch of manual locations that `rdataretriever` checks if the `retriever` isn't found on the path. We need to know where it's hiding so that we can add it to that list.

**Comment by DAPPERstats** [comment]
I'm running this all from the Anaconda prompt

(C:\Users\dappe\Anaconda3) C:\Users\dappe>which retriever
'which' is not recognized as an internal or external command,
operable program or batch file.

(C:\Users\dappe\Anaconda3) C:\Users\dappe>WHERE retriever
C:\Users\dappe\Anaconda3\Scripts\retriever.exe

let me know if you need any other info. thanks!

**Comment by ethanwhite** [comment]
Ah, interesting. OK. Can you do there WHERE line again just using `cmd` instead of the Anaconda prompt. I'm guessing it will no longer find the retriever.

**Comment by DAPPERstats** [comment]
yup:

C:\Users\dappe>WHERE retriever
INFO: Could not find files for the given pattern(s).

**Comment by henrykironde** [comment]
Ah, I think Anaconda script path needs to be added to the path environment variables.
'C:\Users\dappe\Anaconda3\Scripts\' @ethanwhite what do you think

**Comment by ethanwhite** [comment]
Yep. @DAPPERstats I suspect that during install there was an option to add to path or make Anaconda the default Python distribution and you didn't choose it. We could change the manually, but for the sake of understanding the probably would you mind reinstalling Anaconda and looking for those options and choosing to 'add to path' and/or 'make default. I suspect that will fix things. If so we should update the documentation to make this clear.

**Comment by DAPPERstats** [comment]
Yeah, the 'add to PATH' wasn't checked in the installer, and checking it causes text to turn red (saying "this isn't recommended"). 
I'd suggest editing the install instructions on the main data retriever site, which say 
"If you don’t have Python installed we recommend installing Anaconda using the default options in the installer and then running this conda install command."

I uninstalled and reinstalled (with the PATH box checked) Anaconda and then ran the 
conda install retriever -c conda-forge 
command and now everything works peachy keen in R

**Comment by ethanwhite** [comment]
Thanks @DAPPERstats! Apparently Anaconda changed it's installer defaults... again.

@zhangcandrew - if you have a few minutes could you PR a wording change into https://github.com/weecology/retriever-site ?

**Comment by DAPPERstats** [comment]
You're welcome! Glad to help. Thanks for helping track this down!

**Comment by naureen3** [comment]
I can't seem to solve this where ever I type conda it says it's not recognized and when i say where conda it says could not find... I typed cd and gave it the path and it didn't get it... and then i went to advanced settings and tried changing things there and nothing happened :( ... i just want to install lightfm... i tired from everywhere pip... and now that i couldn't do it using pip I tired using conda and that cant happen

**Comment by ethanwhite** [comment]
Hi @naureen3 - thanks for letting us know about your issue. What operating system are you using?
