### ISSUE TITLE
check_for_retriever only working in RStudio

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#122]
In #121 we have a case where Anaconda didn't get added to the path during install. It's in one of the the expected directories and so `check_for_retriever` should have caught and fixed this but... wait for it... there's a difference between how R and RStudio return environmental variables:

In RStudio:

```
> Sys.getenv('HOME')
[1] "C:/Users/ethanwhite/Documents"
```

In R:

```
> Sys.getenv('HOME')
[1] "C:\\Users\\ethanwhite\\Documents"
```

As a result our check for and removal of the `Documents` directory currently doesn't work when not run in RStudio.

**Comment by henrykironde** [comment]
I think we should utilize this function
```
FullPath <- function( ReferencePath, BasePath=getwd()){
  BasePath = normalizePath(BasePath)
  ReferencePath = normalizePath(ReferencePath)
  Path = normalizePath(file.path(BasePath, ReferencePath), mustWork = FALSE)
  return (Path)
}
```
Also Rstuidio sometimes defines its own home path, if i remember.

**Comment by ethanwhite** [comment]
@henrykironde - I agree with the basic approach or using `normalizePath` and was just starting to work on it. Do we need the `BasePath` / `ReferencePath` stuff here since we just want home directories?

**Comment by henrykironde** [comment]
No We don't

**Comment by ethanwhite** [comment]
OK, thanks. I'll work on it unless you're already doing it.

**Comment by henrykironde** [comment]
Not yet looking through the previous PR

**Comment by ethanwhite** [comment]
The code associated with this issue was eliminated as part of @pranita-s's rewrite to use `reticulate`. Thanks @pranita-s!
