### ISSUE TITLE
Update package to handle more customized during installation

### ISSUE THREAD

**Issue by henrykironde** [ropensci/rdataretriever#126]
The current function does not consider some retriever options

```R
    cmd = paste('retriever install', connection, dataset, '--user', conn$user,
                '--password', conn$password, '--host', conn$host, '--port',
                conn$port)
```
We need to provide more options for users to at least provide a customizable install into the databases they want with a name of their choice

**Comment by pranita-s** [comment]
@henrykironde Please elaborate the requirements.
I tried postgres connection to install and included "database_name" and "table _name" in postgres.conn file. It installed the datasets by creating mentioned database and table names in the conn file.

**Comment by henrykironde** [comment]
Could you send me the command you used, just to be clear

**Comment by henrykironde** [comment]
In the config file, remove the table name line. The custom table name was designed for single table datasets like iris. I will raise an issue about that to remove that option or make it better.

**Comment by pranita-s** [comment]
I removed the table line, and install function from environment takes the database name from the postgres.conn file but install function from rdataretriever does not. 
Why are both of them behaving differently?

**Comment by henrykironde** [comment]
It looks like it's a permission issue. May be the `rdataretriever` does not have permission to use that file.

**Comment by henrykironde** [comment]
covered in the fb7d1b9
