### ISSUE TITLE
Replace `bone` variable name

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#135]
I get the idea of `bone` as the thing that the retriever is fetching, but it makes the code difficult to follow for me because it's not very intuitive and I imagine that for non-native speakers or folks who just don't get the joke it's really confusing.

**Comment by pranita-s** [comment]
@ethanwhite What should be the new variable name? data_sets may be? As it holds all the datasets in the form of list.

**Comment by ethanwhite** [comment]
@pranita-s That sounds good, but since dataset (no space) is a commonly acceptable form let's go with `dataset` and skip the underscore.

**Comment by pranita-s** [comment]
I have addressed this issue in the commit https://github.com/ropensci/rdataretriever/pull/134/commits/fd530e966a761fd045db0995581fee2f63b22e7b

**Comment by ethanwhite** [comment]
Fixed by @pranita-s in a12397c7b049d10288e971cffa90e1d1c9d374bb.
