### ISSUE TITLE
Is ecoretriever still available?

### ISSUE THREAD

**Issue by sunyi000** [ropensci/rdataretriever#144]
sorry if this is not the appropriate place to post this question. I'm trying to install ecoretriever by following the instruction here https://github.com/cran/ecoretriever
but it seems to me that it is no longer available, and everything is redirected to rdataretriever?  are these two the same now, or there's another way somewhere to install ecoretriever?

Thank you very much

**Comment by henrykironde** [comment]
@sunyi000, the software is now rdataretriever. 
Let me know when you find any problem installing the software.
