### ISSUE TITLE
Different behavior of Travis tests for same PR on the master and its forked repo

### ISSUE THREAD

**Issue by pranita-s** [ropensci/rdataretriever#157]
The PRs #153,  #154, #155 are failing when created for ``ropensci/rdataretriever`` but the PR of the same branch created for the forked repo ``henrykironde/rdataretriever`` passes all the tests (Ref: https://github.com/henrykironde/rdataretriever/pull/4)

**Comment by henrykironde** [comment]
This has not been seen recently. I will close it for now.
