### ISSUE TITLE
Add functionality to reset a specific dataset

### ISSUE THREAD

**Issue by harshitbansal05** [ropensci/rdataretriever#180]
The functionality to reset a specific dataset can be added similar to Retriever.

**Comment by harshitbansal05** [comment]
@henrykironde, if possible can I work on it?

**Comment by ethanwhite** [comment]
Hi @harshitbansal05 - yes, it would be great if you could wrap the functionality you added to the retriever in https://github.com/weecology/retriever/issues/1241 for the R package. Thanks!
