### ISSUE TITLE
Possible error in download function regarding argument sub_dir

### ISSUE THREAD

**Issue by harshitbansal05** [ropensci/rdataretriever#181]
There is a possible error in the download function regarding the argument `sub_dir`. The current code is:
```
if (sub_dir)
    r_data_retriever$download(dataset = dataset, path = path)
  else
    r_data_retriever$download(dataset = dataset)
```
However, the argument `sub_dir` decides whether to download all the files in a subdirectory inside the path argument. So, path should be passed to the download function even if `sub_dir` is False. Kindly correct me if I am wrong.

**Comment by harshitbansal05** [comment]
@henrykironde could you please add your views on this?

**Comment by henrykironde** [comment]
Sorry for the late reply, I have been busy. I will look at it right now

**Comment by henrykironde** [comment]
I think we should change this to `data_dir` and this applies to the retriever too

**Comment by harshitbansal05** [comment]
@henrykironde sorry, but I didn't quite get you. Shouldn't we just change the entire if-else statement to simple: `r_data_retriever$download(dataset = dataset, path = path, sub_dir=sub_dir)`, and leave it to Retriever to handle? Please correct me if I am wrong.

**Comment by henrykironde** [comment]
@harshitbansal05, looks like it, But I have to get time to go through the the download function in the python file. 
From a quick look, it seems that  r_data_retriever$download(dataset = dataset, path = path, sub_dir=sub_dir) works fine. 

However, initially what `subdir` was doing was to keep files in a different directory when downloaded.
We added data_dir to other file engines and I have a feeling this is doing almost the same  as data_dir.

So we may need to really do some sample tests and see if we can clean up some of that code without breaking backward compatibility.

**Comment by ethanwhite** [comment]
The conditional usage of this code was removed at some point so I think this has been addressed. If there is still an issue with the new code feel free to open a new issue.
