### ISSUE TITLE
version bump or update instructions for installing from github

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rdataretriever#182]
It looks like there was a change in `install_csv` that adds `data_dir` as an optional argument. After @ethanwhite's [PR in MATSS](weecology/MATSS/pull/105) to use this functionality, I had trouble running this on my local machine.

Using `pip install git+https://git@github.com/weecology/retriever.git` to update retriever to the dev version didn't seem to work, but cloning the repository and running `pip install .` inside the source directory worked.

Looking more closely at the output from trying to install from github, I see
```
Requirement already satisfied (use --upgrade to upgrade): retriever==2.2.1.dev0 from 
git+https://git@github.com/weecology/retriever.git in /Users/hye/anaconda3/lib/python3.7/site-
packages
```

So I think either a change in version # or an update to the installation instructions on the website would fix this.

**Comment by henrykironde** [comment]
Could you try `pip install git+https://git@github.com/weecology/retriever.git  --upgrade` and install `rdataretriever` from master.
