### ISSUE TITLE
Releasing to CRAN

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#190]
We're about to release 2.0.0, which is major rewrite to leverage `retriculate` for wrapping the Python API directly and adding a bunch of new functionality from it.

@dmcglinn - we wanted to know how you wanted to handle releasing this to CRAN. We're happy for you to do it if you want to, but we're also happy to take over that responsibility if you prefer. Just let us know which route you want to go and we can coordinate from there in this issue.

**Comment by dmcglinn** [comment]
Hey @ethanwhite et al. great work on all the updates to the package! I've taken a back seat to developing this package, and I don't feel I'm the best person to be considered first author on this release. Is anyone interested in stepping into this role for this package? @henrykironde perhaps. If so maybe they could update the package description file and lead the CRAN submission. If folks are happier with me as the first author then I can shield others from the horrors of CRAN submission and take care of that for the team ;P

**Comment by henrykironde** [comment]
Thanks folks. Hello @dmcglinn hope you are fine. I personally think the authorship list is perfect as it is right now. Like you mentioned, the main horror is CRAN submission. I do believe you are super busy but if you could help in this release and draft a few release steps for the future(may be as an issue), that would be great. I will do the formatting where needed and I will add them to developer docs for the package.
In case you are busy, I could also talk to @ha0ye

**Comment by ha0ye** [comment]
Assuming the package passes all CRAN checks and the "Description" field in DESCRIPTION is unchanged, submitting updates is usually smooth, in my experience. (My biggest headaches have been on repeated back and forths over wording and formatting of the "Description"...)

**Comment by henrykironde** [comment]
Okey, I guess I will have to change some testing on this to be ready. Thanks @ha0ye

**Comment by henrykironde** [comment]
@dmcglinn, we have this package ready for release. I am not sure if it will be fine since I removed you from creator to author. I suspect we may need to add you and change that after release. let know in case of any thing needed

**Comment by dmcglinn** [comment]
Hey @henrykironde changing me from creator to author looked great. I think that's the right call. Do you want me to submit it to CRAN still or do you want to do the honors?

**Comment by ha0ye** [comment]
FYI, for a transfer of maintainer-ship, CRAN will contact both the newly listed maintainer (@henrykironde) and the previously listed maintainer (@dmcglinn) to verify. It doesn't matter who uploads - I could do it, even. :)

**Comment by henrykironde** [comment]
Yes @ha0ye  do it if you can. Do we need to first create a GitHub release?

**Comment by ha0ye** [comment]
> Yes @ha0ye do it if you can. Do we need to first create a GitHub release?

Nope, not necessary.

**Comment by henrykironde** [comment]
Great, super excited to install the release

**Comment by ha0ye** [comment]
I ran into some errors when running the tests - it looks like maybe they assume that postgre and mysql are installed, and might fail when they are not?

**Comment by henrykironde** [comment]
Thanks @ha0ye, That is true but it is fine, we have handled that for CRAN.
Tests locally will need developers to have Postgres and MySQL servers.
However, we also have the docker environment test capabilities where you do not need to install these servers.
Use` docker-compose run rdata Rscript load_and_test.R` to test. 
ref: https://github.com/ropensci/rdataretriever#using-dockers

**Comment by henrykironde** [comment]
Thank you @ha0ye 👍, I received the CRAN email and accepted, we are waiting for @dmcglinn. I think we shall be up and running after the holidays

> package rdataretriever_2.0.0.tar.gz has been auto-processed.
> We are waiting for confirmation from the old maintainer address now.

**Comment by henrykironde** [comment]
Thanks again everyone who made this release possible, great work from everyone.
