### ISSUE TITLE
Add Windows specific install instructions

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#196]
(if you haven't already)

1. Install Rtools
2. Install devtools
3. Possibly (1 computer so far) manually install Rcpp
4. Continue with the rest of the instructions
6. (needed on some computers) Restart RStudio after install rdataretriever package

**Comment by henrykironde** [comment]
Additionally,
Since Ropensci has now started hosting docs, we should go ahead and merge the docs in these two locations 
https://docs.ropensci.org/rdataretriever,
https://retriever.readthedocs.io/en/latest/rdataretriever.html
And make sure they sync

**Comment by henrykironde** [comment]
@Ethan thanks for instructions, I will try the above on a fresh windows system and update accordingly.

**Comment by ethanwhite** [comment]
Ooh nice. Yeah, I think moving everything to the ropensci docs is definitely the way to go!

Also, since I wasn't super clear when I added these, this is temporarily until `reticulate` gets a new release. I'm going to submit an issue over there this evening in the hopes that they can do this quickly.
