### ISSUE TITLE
Would Rshiny server help side step install problems

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rdataretriever#201]
Hey folks, I was just watching from the side-lines as you fight the good fight on the install wars. Have you thought at all of trying to provide this tool as an Rshiny server that would provide users an install free work flow. The the user just navigates to the appropriate url to interact with it. I've been watching the microbe bioinformatics folks develop their tools and they seem to often favor web apps maybe to avoid install problems. Anyways its just a thought. I'm not suggesting to not continue to develop this as a stand alone R package just that a function could be added to launch a shiny gui which could be hosted online.

**Comment by ethanwhite** [comment]
At that point we run into the redistribution issue again, so we'd have to drop anything without a CC-BY or CC0 license. It would also prevent installing directly into databases, etc. If we were going to go that route I think we'd just drop the R package entirely, run the Python package once a week get the the most updated data and then just serve it was csv files.

All of the issues we're currently encountering appear to be bugs in `reticulate`, not `rdataretriever`, so I'm hopefully they'll get fixed here at some point.
