### ISSUE TITLE
[enhancement] check retriever version for compatibility

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rdataretriever#206]
I ran into a silently failing error, due to having an updated install of `retriever`, but an older version of `rdataretriever`. See https://github.com/weecology/MATSS/issues/152 for details and associated Travis log.

It would be nice to include a check that the installed version of rdataretriever works with the installed version of retriever (or perhaps some other check that is more verbose when an action fails).

**Comment by henrykironde** [comment]
Yes should definitely think about this. We have been failing for sometime because of a dependency that changed and a few days ago, it was updated/repaired.

**Comment by ethanwhite** [comment]
Looks like we'd probably do this by:

1. Adding the requirement to a carefully structured `SystemRequirements` line in `DESCRIPTION`
2. Accessing the information with:

  ```R
  packageDescription('rdataretriever', fields = "SystemRequirements")
  ```

3. Parsing it to get the minimum retriever requirement.
4. Check the installed version of the `retriever` (which I'm still trying to figure out how to do).

**Comment by ha0ye** [comment]
I don't think there's a standard syntax for SystemRequirements formatting, but the rstudio `keras` package has an example.

https://github.com/rstudio/keras/blob/master/DESCRIPTION
> SystemRequirements: Keras >= 2.0 (https://keras.io)

**Comment by ethanwhite** [comment]
Thanks @ha0ye!

@henrykironde has now added a `data_retriever_version()` function that I just merged to handle step 4.
