### ISSUE TITLE
capture output of `get_citation` to return (instead of printing to the console)

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rdataretriever#207]
per conversation with @ethanwhite, related to weecology/MATSS#160

`rdataretriever::get_citation("iris")` will print the citation info to the console, but the ideal functionality is to return it as a string, so that users can store it. (or by default, the return value gets printed if the return value isn't handled).

I think this can be fixed pretty easily, by adding the `intern = TRUE` argument to the call to `run_cli`.

So the fix for `get_citation()` is:
```r
get_citation <- function(dataset) {
  run_cli(paste("retriever citation", dataset), intern = TRUE)
}
```

LMK if you'd like a PR with associated test.

**Comment by ethanwhite** [comment]
Related to https://github.com/weecology/retriever/issues/1419. I like the quick in @ha0ye's proposal and then once https://github.com/weecology/retriever/issues/1419 is implemented then we can update this to actually wrap the Python.

@ha0ye - a PR with a test would be awesome if you have time. Thanks!
