### ISSUE TITLE
Docker images are failing to install

### ISSUE THREAD

**Issue by henrykironde** [ropensci/rdataretriever#209]
There must be some changes made that are affecting the installation of programs.
I have put an issue and hopefully some folks may be able to point us in the right direction.

https://github.com/rocker-org/rocker-versioned/issues/189

**Comment by ethanwhite** [comment]
This is failing locally for me on 18.04 as well. I wonder if the MySQL 5.7 image got removed from docker hub or something...

**Comment by ethanwhite** [comment]
Correction: My attempted fix in #210 is broken locally on 18.04. The current `Dockerfile` is not broken locally on 18.04.

**Comment by ethanwhite** [comment]
Best current guess is that the difference between `rdataretriever` (failing) and `retriever` (working) is that `retriever` is built on Ubuntu (18.04) and the `rocker` images are built on Debian (Buster). Ubuntu 18.04 is based on Debian Buster, but I'm guessing they do something different to address the naming issue identified in the rocker issue.

**Comment by ethanwhite** [comment]
@henrykironde - looks like this was fixed with the shift to MariaDB in 266f9c52c1d60761b6984b367f692a0260fda06b. If so we can go ahead and close this one.

**Comment by ethanwhite** [comment]
If it was fixed we should also report back in the associated Rocker issue and close it.

**Comment by ethanwhite** [comment]
Closing for now since everything seems to be running smoothly. Feel free to reopen if I've missed something.
