### ISSUE TITLE
warning/error with `.onLoad()`

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rdataretriever#212]
Newer versions of `reticulate` check for initializing python, which currently occurs when loading `rdataretriever`. In the latest version of reticulate, this is a warning, but was previously an error, so may be a larger issue than currently.

Following the guidelines in https://rstudio.github.io/reticulate/articles/package.html, I think the `.onLoad()` function can be simplified to just the one line:
```r
.onLoad <- function(libname, pkgname) {
  ## assignment in parent environment!
  retriever <<- reticulate::import("retriever", delay_load = TRUE)
}
```

And `install_python_modules()` can be an exported function (perhaps renamed to `install_retriever()` OR left out entirely, since it seems like the rdataretriver docs all reference using `reticulate::py_install()` to install retriever from within R, thus duplicating the functionality of this function.

**Comment by ethanwhite** [comment]
Fixed in 5d708011b3052a7999b5a890ed308dcc7f7781a8. Thanks @ha0ye!
