### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rdataretriever#214]
(related issues: #199, #197, #196, #176)

Reticulate ver 1.15 is on CRAN (as of 2020-04-02), and there's now better functionality for installing miniconda and creating an environment exclusively for python packages that link to R.

I think this is a good time to update the installation docs to include the miniconda route, and perhaps think about releasing a new version of rdataretriever to CRAN, as well.

**Comment by ethanwhite** [comment]
Thanks @ha0ye and sorry for the delay. I'm going to start working on this over the next week or so. The docs still seem pretty thin on having `reticulate` do a `miniconda` install. Have you seen any write up on this other than the official docs?

**Comment by ethanwhite** [comment]
Relevant docs:
* https://rstudio.github.io/reticulate/reference/install_miniconda.html
* https://rstudio.github.io/reticulate/reference/miniconda_path.html
* https://rstudio.github.io/reticulate/reference/miniconda_update.html
* https://rstudio.github.io/reticulate/articles/package.html

**Comment by ha0ye** [comment]
I did not, but ended up putting some instructions together as part of the readme to distribute in MATSS compendia. Example here (including installing the dev version of retriever):
https://github.com/weecology/MATSSdemo#downloading-additional-datasets

**Comment by ethanwhite** [comment]
Thanks @ha0ye!
