### ISSUE TITLE
Checklist for 2.1.0 release

### ISSUE THREAD

**Issue by ha0ye** [ropensci/rdataretriever#229]
With the updated docs and new features, I think it'd be timely to think about what else to take care of for a 2.1.0 release. (since 2.0.0 is now approaching a year on CRAN, and it seems like there's been some substantial under-the-hood fixes and added functionality)

**Comment by ethanwhite** [comment]
Agreed. I think the only question is the version. We're getting ready to release retriever 3.0 and there are changes here that require retriever 3.0, so I think we probably want to make this 3.0.0.

**Comment by ethanwhite** [comment]
I don't see any blockers in the issue queue, but if anyone sees anything that needs to go in before the next release we should go ahead and identify those now.
