### ISSUE TITLE
Tests of new installation instructions

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#230]
Thanks to some improvements in `reticulate` (which is how we interact with Python from R) we've been able to simplify and hopefully stabilize installation. We're looking for a few volunteers to try out these instructions to help ensure that they are as easy as possible to understand and follow and that they work well across an range of systems (operating systems, versions, etc.).

If you have ~10 minutes and would like to help out with testing please do the following.

1. If already installed, uninstall current installations of rdataretriever, `remove.packages('rdataretriever`), and retriever, `pip uninstall retriever` or `conda remove retriever`.
2. Follow the instructions here: https://github.com/ropensci/rdataretriever#basic-installation
3. Report back to this issue with your experience and any recommended changes. This includes reports of success. Please provide your operating system as well if that's something you're happy to share.

**Comment by dill** [comment]
:+1: This worked fine for me, on a system that already had `reticulate` working (following the basic installation instructions, I was asked to install `miniconda` which I did and it worked fine), see session info below.

One suggestion: rather than asking the user to follow the instructions [here](https://github.com/ropensci/rdataretriever#basic-installation), perhaps it's possible to do something similar to what [`greta`](https://github.com/greta-dev/greta) does and allow installation of the R package first, then on load checks to see if the correct `conda` environment is available and has the requisite packages/versions installed? I think [this code](https://github.com/greta-dev/greta/blob/master/R/utils.R#L52) is the kind of thing that would be necessary. Don't think it's a dealbreaker, just a suggestion to minimize friction.

Some session info:

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.0       Matrix_1.2-18        Rcpp_1.0.4.6
[4] reticulate_1.16      grid_4.0.0           jsonlite_1.7.0
[7] lattice_0.20-41      rdataretriever_2.0.0
```

**Comment by gavinsimpson** [comment]
The basic installation steps all worked fine for me on Linux (Fedora 32) and it's version of R installed (R 3.6.3 currently)

```
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                          
 version  R version 3.6.3 (2020-02-29)   
 os       Fedora 32 (Workstation Edition)
 system   x86_64, linux-gnu              
 ui       X11                            
 language (EN)                           
 collate  en_US.utf8                     
 ctype    en_US.utf8                     
 tz       America/Regina                 
 date     2020-07-14                     

─ Packages ───────────────────────────────────────────────────────────────────
 package        * version date       lib source        
 assertthat       0.2.1   2019-03-21 [1] CRAN (R 3.6.3)
 backports        1.1.8   2020-06-17 [1] CRAN (R 3.6.3)
 callr            3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cli              2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon           1.3.4   2017-09-16 [1] CRAN (R 3.6.3)
 desc             1.2.0   2018-05-01 [1] CRAN (R 3.6.3)
 devtools         2.3.0   2020-04-10 [1] CRAN (R 3.6.3)
 digest           0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 ellipsis         0.3.1   2020-05-15 [1] CRAN (R 3.6.3)
 fansi            0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 fs               1.4.2   2020-06-30 [1] CRAN (R 3.6.3)
 glue             1.4.1   2020-05-13 [1] CRAN (R 3.6.3)
 jsonlite         1.7.0   2020-06-25 [1] CRAN (R 3.6.3)
 lattice          0.20-41 2020-04-02 [1] CRAN (R 3.6.3)
 magrittr         1.5     2014-11-22 [1] CRAN (R 3.6.3)
 Matrix           1.2-18  2019-11-27 [2] CRAN (R 3.6.3)
 memoise          1.1.0   2017-04-21 [1] CRAN (R 3.6.3)
 pkgbuild         1.0.8   2020-05-07 [1] CRAN (R 3.6.3)
 pkgload          1.1.0   2020-05-29 [1] CRAN (R 3.6.3)
 prettyunits      1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx         3.4.3   2020-07-05 [1] CRAN (R 3.6.3)
 ps               1.3.3   2020-05-08 [1] CRAN (R 3.6.3)
 R6               2.4.1   2019-11-12 [1] CRAN (R 3.6.3)
 rappdirs         0.3.1   2016-03-28 [1] CRAN (R 3.6.3)
 Rcpp             1.0.5   2020-07-06 [1] CRAN (R 3.6.3)
 rdataretriever * 2.0.0   2019-05-25 [1] CRAN (R 3.6.3)
 remotes          2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 reticulate       1.16    2020-05-27 [1] CRAN (R 3.6.3)
 rlang            0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rprojroot        1.3-2   2018-01-03 [1] CRAN (R 3.6.3)
 sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
 testthat         2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 usethis          1.6.1   2020-04-29 [1] CRAN (R 3.6.3)
 withr            2.2.0   2020-04-20 [1] CRAN (R 3.6.3)

[1] /home/gavin/R/x86_64-redhat-linux-gnu-library/3.6
[2] /usr/lib64/R/library
[3] /usr/share/R/library
```

**Comment by mdsumner** [comment]
Basic Installation worked fine for me on Windows and also on Linux (as a normal user)

One tiny thing, I noticed as I happened to use a "fresh" user account on Linux that had no ~/R/ folder - the AskYesNo process for install.packages means the instructions aren't "bulk copy/paste" ready. You could add that nuance *run each line in turn ...*, I'm not sure if `ask = FALSE` fits the bill here.

**Comment by ethanwhite** [comment]
Thanks @dill @gavinsimpson and @mdsumner - much appreciated.

That's a great suggestion @dill - I'll put it on the To Do list.

Thanks for catching that @mdsumner I'll see if we can avoid that automatically. Fortunately should be an edge case.
