### ISSUE TITLE
 CRAN submission update

### ISSUE THREAD

**Issue by henrykironde** [ropensci/rdataretriever#242]
package rdataretriever_3.0.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200727_223546/Windows/00check.log>
Status: 2 NOTEs
Debian: <https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200727_223546/Debian/00check.log>
Status: OK

Last released version's CRAN status: NOTE: 3, OK: 9
See: <https://CRAN.R-project.org/web/checks/check_results_rdataretriever.html>

CRAN Web: <https://cran.r-project.org/package=rdataretriever>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200727_223546/>
The files will be removed after roughly 7 days.

No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Henry Senyondo <henrykironde@gmail.com>'

Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: whether the namespace can be loaded with stated dependencies, Result: NOTE
  Warning in system2(command = python, args = paste0("\"", config_script,  :
    running command '"C:/Users/ligges/AppData/Local/r-miniconda/envs/r-reticulate/python.exe" "d:/RCompile/CRANpkg/lib/4.1/reticulate/config/config.py"' had status 2

  A namespace must be able to be loaded with just the base namespace
  loaded: otherwise if the namespace gets loaded by a saved object, the
  session will be unable to start.

  Probably some imports need to be declared in the NAMESPACE file.

**Comment by ethanwhite** [comment]
I did a little looking around and my guess is that this is being triggered by https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L773.

@henrykironde have you been able to replicate this note locally? I can't replicate it on my machine even using `--as-cran`? If you're getting the note locally can you remove that function from `.onLoad` and see if that removes it?

**Comment by henrykironde** [comment]
Dear maintainer,

package rdataretriever_3.0.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200803_172854/Windows/00check.log>
Status: 3 NOTEs
Debian: <https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200803_172854/Debian/00check.log>
Status: 1 NOTE

Last released version's CRAN status: OK: 12
See: <https://CRAN.R-project.org/web/checks/check_results_rdataretriever.html>

CRAN Web: <https://cran.r-project.org/package=rdataretriever>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200803_172854/>
The files will be removed after roughly 7 days.

No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: NOTE
  Maintainer: 'Henry Senyondo <henrykironde@gmail.com>'

  Found the following (possibly) invalid URLs:
    URL: http://nsf.gov/ (moved to https://nsf.gov/)
      From: README.md
      Status: 200
      Message: OK
    URL: http://nsf.gov/awardsearch/showAward.do?AwardNumber=0953694 (moved to https://nsf.gov/awardsearch/showAward?AWD_ID=0953694)
      From: README.md
      Status: 200
      Message: OK
    URL: http://ropensci.org (moved to https://ropensci.org/)
      From: README.md
      Status: 200
      Message: OK
    URL: https://docs.ropensci.org/rdataretriever (moved to https://docs.ropensci.org/rdataretriever/)
      From: DESCRIPTION
      Status: 200
      Message: OK

Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: whether the namespace can be loaded with stated dependencies, Result: NOTE
  Warning in system2(command = python, args = paste0("\"", config_script,  :
    running command '"C:/Users/ligges/AppData/Local/r-miniconda/envs/r-reticulate/python.exe" "d:/RCompile/CRANpkg/lib/4.1/reticulate/config/config.py"' had status 2

  A namespace must be able to be loaded with just the base namespace
  loaded: otherwise if the namespace gets loaded by a saved object, the
  session will be unable to start.

  Probably some imports need to be declared in the NAMESPACE file.

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: NOTE
  Maintainer: 'Henry Senyondo <henrykironde@gmail.com>'

  Found the following (possibly) invalid URLs:
    URL: http://nsf.gov/ (moved to https://nsf.gov/)
      From: README.md
      Status: 200
      Message: OK
    URL: http://nsf.gov/awardsearch/showAward.do?AwardNumber=0953694 (moved to https://nsf.gov/awardsearch/showAward?AWD_ID=0953694)
      From: README.md
      Status: 200
      Message: OK
    URL: http://ropensci.org (moved to https://ropensci.org/)
      From: README.md
      Status: 200
      Message: OK

**Comment by henrykironde** [comment]
new results 
https://win-builder.r-project.org/8CwpW6uy2b78
https://win-builder.r-project.org/297R0yK5pMfi
https://win-builder.r-project.org/b80Q9j05LzoA

**Comment by henrykironde** [comment]
https://win-builder.r-project.org/3m09aO01Mw78

**Comment by henrykironde** [comment]
https://win-builder.r-project.org/Qm3r5qHNGrh3

**Comment by henrykironde** [comment]
https://win-builder.r-project.org/AP9pAPnGWAru/
looks like the last tested version has no notes https://win-builder.r-project.org/AP9pAPnGWAru/

**Comment by henrykironde** [comment]
@ethanwhite  this is the latest from CRAN

Dear maintainer,

package rdataretriever_3.0.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200804_163723/Windows/00check.log>
Status: 2 NOTEs
Debian: <https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200804_163723/Debian/00check.log>
Status: OK

Last released version's CRAN status: OK: 12
See: <https://CRAN.R-project.org/web/checks/check_results_rdataretriever.html>

CRAN Web: <https://cran.r-project.org/package=rdataretriever>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/rdataretriever_3.0.0_20200804_163723/>
The files will be removed after roughly 7 days.

No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Henry Senyondo <henrykironde@gmail.com>'



Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: whether the namespace can be loaded with stated dependencies, Result: NOTE
  Warning in system2(command = python, args = paste0("\"", config_script,  :
    running command '"C:/Users/ligges/AppData/Local/r-miniconda/envs/r-reticulate/python.exe" "d:/RCompile/CRANpkg/lib/4.1/reticulate/config/config.py"' had status 2

  A namespace must be able to be loaded with just the base namespace
  loaded: otherwise if the namespace gets loaded by a saved object, the
  session will be unable to start.

  Probably some imports need to be declared in the NAMESPACE file.
