### ISSUE TITLE
[JOSS]: Request for authorship and acknowledgement 

### ISSUE THREAD

**Issue by henrykironde** [ropensci/rdataretriever#250]
- [x] @dmcglinn 
- [x] @henrykironde 
- [x] @karthik 
- [x] @ethanwhite 
- [x] @pranita-s 
- [x] @ha0ye 
- [x] @harshitbansal05 
- [x] @maxpohlman 
- [x] @apoorvaeternity 
- [x] @sdtaylor 
- [x] @davharris 
- [x] @Pakillo 
- [x] @jeroen

Hi everyone, 

We do thank you for each and every contribution you have made to the the Rdataretriever. We are here by requesting for you permission to be added as a co-author for the Rdataretriever tool. We plan to submit the tool to  Journal of Open Source Software (JOSS) https://joss.theoj.org/. Please provide me with this information thank you 

```
 - name: Henry Senyondo
   affiliation: Department of Wildlife Ecology and Conservation, University of Florida
   orcid: 0000-0001-7105-5808
 ````

The orchid number can be obtained by registering here https://orcid.org/

**Comment by Pakillo** [comment]
Thanks @henrykironde et al. Here is my info:

- name: Francisco Rodríguez-Sánchez
  affiliation: Departamento de Biología Vegetal y Ecología, Universidad de Sevilla. 
  orcid: 0000-0002-7981-1599

Cheers!

**Comment by ha0ye** [comment]
Thanks for including me. Here is my info:
```
 - name: Hao Ye
   affiliation: Health Science Center Libraries, University of Florida
   orcid: 0000-0002-8630-1458
```

**Comment by sdtaylor** [comment]
Thanks Henry. Mines is:

```
- name: Shawn D Taylor
  affiliation: USDA-ARS Jornada Experimental Range
  orcid: 0000-0002-6178-6903
```

**Comment by dmcglinn** [comment]
Way to go Henry! Here's my info:

```
- name: Daniel J. McGlinn
   affiliation: Department of Biology, College of Charleston
   orchid: 0000-0003-2359-3526
```

**Comment by maxpohlman** [comment]
Congrats and good luck with the submission. My info:

```
- name: Max Pohlman
   affiliation: Department of Agricultural Economics, Sociology, and Education, Penn State University
   orcid: 0000-0003-2325-6984

```

**Comment by karthik** [comment]
```
- name: Karthik Ram
  affiliation: Berkeley Institute for Data Science, University of California, Berkeley
  orcid: 0000-0002-0233-1757
```

**Comment by pranita-s** [comment]
Congrats and good luck with the submission ! 

```
-name: Pranita Sharma
 affiliation: North Carolina State University.   
 orcid: 0000-0002-5871-380X. 
```

**Comment by jeroen** [comment]
```
-name: Jeroen Ooms
 affiliation: Berkeley Institute for Data Science, University of California, Berkeley
 orcid: 0000-0002-4035-0289
```

**Comment by harshitbansal05** [comment]
-name: Harshit Bansal
affiliation: Department of Electronics and Communication, Indian Institute of Technology, Roorkee
orcid: 0000-0002-3285-812X

**Comment by harshitbansal05** [comment]
```
-name: Harshit Bansal
affiliation: Department of Electronics and Communication, Indian Institute of Technology, Roorkee
orcid: 0000-0002-3285-812X
```

**Comment by henrykironde** [comment]
Thanks everyone

**Comment by davharris** [comment]
Hi, sorry for the delay replying to this. Looks like you already have me listed, but let me know if you need anything else. Thanks, and good luck with the submission!
