### ISSUE TITLE
suggestion remotes::install_github in stead of devtools::install_github

### ISSUE THREAD

**Issue by RMHogervorst** [ropensci/rdataretriever#259]
devtools::install_github("ropensci/rdataretriever")
is calling remotes::install_github() underneath. 

Devtools has a lot of dependencies that you do not strictly need if you only want to install a package from github.

This is low priority and only a suggestion.

**Comment by henrykironde** [comment]
Thanks @RMHogervorst, I will confirm the suggestion with some folks on the team. I encountered and error that was solved by including `devtools`. I will update the issue tomorrow.
