### ISSUE TITLE
[optional] consider more explanation about commit

### ISSUE THREAD

**Issue by RMHogervorst** [ropensci/rdataretriever#264]
I see some value in the provenance functionality, but it isn't very clear to me, and the examples in the readme do not work if you try to follow them in a fresh session. 

Maybe a small example with

- what is the problem (track what actions you performed on the data?)
- what is the current solution (just manually writing it out in a log I guess?)
- What would this `commit()` action do for me?
- perform some steps, with commit() after and end with commit_log?

As an aside the current description of `commit()` is "Commit a dataset" and honestly confused me a bit. How is this different from git commit? Commit to what?

**Comment by henrykironde** [comment]
This has been covered
