### ISSUE TITLE
Author list in repo needs to align with the list on Zenodo

### ISSUE THREAD

**Issue by henrykironde** [ropensci/rdataretriever#286]
The current author list is Zenodo is
```
Dan McGlinn; Ethan White (he/him); henry senyondo; Pranita Sharma; Hao Ye; Apoorva Pandey; Harshit Bansal; Max Pohlman; Francisco Rodriguez-Sanchez; Shawn Taylor; David J. Harris; Frederick Boehm; Jeroen Ooms
UC Berkeley
; Karthik Ram
```

This needs to align with the author list in the paper and Description files.

**Comment by henrykironde** [comment]
ref: https://github.com/openjournals/joss-reviews/issues/2800#issuecomment-749793727

**Comment by ethanwhite** [comment]
@henrykironde - did you want me to update the metadata directly in the current release on Zenodo? I'm pretty sure I can do that.

**Comment by ethanwhite** [comment]
I went ahead and updated the meta data so take a look and see if that takes care of what you need:
https://zenodo.org/record/4314115
