### ISSUE TITLE
Add dependencies of the vignette under Suggests in DESCRIPTION?

### ISSUE THREAD

**Issue by maelle** [ropensci/rdataretriever#293]
E.g. raster isn't listed, see the failure https://github.com/r-universe/ropensci/runs/4511982732?check_suite_focus=true

**Comment by maelle** [comment]
The failure is

```r
Reading 'vignettes/breed-bird-survey-analysis.Rmd'
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 30-36 (breed-bird-survey-analysis.Rmd) 
Error in library(raster) : there is no package called 'raster'
--------------------------------------------------------------------------------
Error : Failed to render RMarkdown
```

**Comment by henrykironde** [comment]
@maelle is this still failing? Raster package published new version on 2021-12-23

**Comment by maelle** [comment]
:wave: @henrykironde from https://ropensci.r-universe.dev/ui#builds

the error is now https://github.com/r-universe/ropensci/runs/4848897897?check_suite_focus=true

Should the vignette be pre-computed? Cf https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by henrykironde** [comment]
Thanks @maelle, for this job we require Python and R in the vm/image. I could try to use the pre-computed vignette but the drawback would be updating the vignette overtime. Is there a way we could configure the dependencies(Python) for the jobs?

**Comment by maelle** [comment]
@jeroen is that a system dependency that'd be possible in the docs building infrastructure?

**Comment by henrykironde** [comment]
Yes, the tool relies on reticulate to convert Python objects to R

**Comment by maelle** [comment]
See #296, thanks to @jeroen
