### ISSUE TITLE
Consider submitting to Journal of Open Source Software

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#68]
The Journal of Open Source Software is a really cool initiative to help provide review and credit for software in an academic context. Publishing there could be a good way for @dmcglinn to get some credit for this great work in a way his college will related to.

Looking at their check list there are a few things we'd need to do:

- [x] Write an abstract level summary. This is what becomes the formal paper.
- [x] Archive the code on Zenodo or Figshare
- [x] Tweak the LICENSE file handling so that it can contain the actual license
- [x] Add some automated tests
- [x] Maybe a little bit of additional documentation

This seems like less than a days worth of work in total and I'd be happy to help out if this is something we want to do.

**Comment by dmcglinn** [comment]
this sounds like a cool idea @ethanwhite thanks for the encouragement. I'll look into this and get back to you likely in August. Ping me if you do not hear from me.

**Comment by dmcglinn** [comment]
After adding the data mobilization meeting at iDiv I'm more motivated to pursue some kind of publication to get the word about the package. Folks were more excited and surprised by the approach then I expected. I think this is due in part to others finally realizing that there are a lot of barriers to resharing data they have compiled themselves. Folks still don't seem quite aware enough of the problem of redundancy and variation in data cleaning that the retriever can provide a means for helping to fix. Some of the attendees also mentioned sending a paper to MEE as an Applications paper (which are all open access). They have a 3000 word limit. Many of the Applications papers are R packages (so it would be appropriate):
http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/features/applicationpapers.html

What do you think @ethanwhite we could try to MEE first if we're rejected then we could go try Journal of Open Source Software second? The JOSS submission process does seem much easier to carry out and would require less time in developing the paper which are just a simple summery.

**Comment by ethanwhite** [comment]
I have a personal preference for JOSS for a few reasons:

1. Now that we are moving beyond the ecology space it seems a little strange to have the canonical software paper/citation for the R package be in an ecology journal.
2. Last time I looked MEE Applications papers weren't actually open access, they were just free to read. I think this goes against the open source ethos of the packages they are advertising. (but it would be great if they've changed this)
3. My impression is that MEE doesn't actually review they software but just the paper about the software. This has lead to them featuring software for which there isn't even a source repo or a release at the time of publication. In contrast JOSS actually reviews the software and my hope is that as a result it will increasingly become a valuable badge for software projects indicating a basic level of  quality.
4. It's quicker and easier, which increases the probability that it gets done and decreases the amount of time we have to take away from other things to do it. We don't have to write an entire paper, we just need to add some things like tests that we should have running anyway, set up Zenodo archiving, and go through the review process.

That said, I understand that there are some career  and ecology focused outreach arguments for choosing MEE and I'm happy to continue the conversation.

**Comment by ethanwhite** [comment]
I just set up Zenodo archiving (which we'll want regardless of where we go). Next time we release it will automatically archive to Zenodo.
