### ISSUE TITLE
Explore how tensorflow handles Python bindings

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#72]
Our bindings to the core retriever's CLI have been fragile due to how R handles `system` calls across operating systems. There have also been additional issues with calling the retriever from RStudio due to how RStudio handles paths.

RStudio has just started developing a [`tensorflow` package](https://github.com/rstudio/tensorflow), which if I understand it correctly is basically a bunch of bindings to the `tensorflow` Python package. It would be good to spend some time looking at how they accomplish this and see if it might be a more stable solution to running the retriever from R.

**Comment by ethanwhite** [comment]
@davharris - would be curious to hear what you think about how they've handled this since you're playing around with it.

**Comment by davharris** [comment]
I think this autoconf script does most of the heavy lifting? https://github.com/rstudio/tensorflow/blob/master/configure.ac

Looks like there's more [here (C++)](https://github.com/rstudio/tensorflow/blob/master/src/python.cpp) and[ here (R)](https://github.com/rstudio/tensorflow/blob/master/R/python.R).

Maybe they'll extract the parts that don't specifically deal with TF as a new R/Python bridge?

**Comment by davharris** [comment]
Turns out what they're doing is incompatible with Anaconda (at least on the Mac). Not sure what else I can contribute here with my knowledge of Python and bash.

**Comment by ethanwhite** [comment]
Thanks Dave!

**Comment by henrykironde** [comment]
@davharris based on the previous comment (below) could you try to relocate the files. The urls are broken
```
I think this autoconf script does most of the heavy lifting? https://github.com/rstudio/tensorflow/blob/master/configure.ac

Looks like there's more here (C++) and here (R).
```

**Comment by ethanwhite** [comment]
After @sdtaylor's fixes to our Windows/RStudio issues I'm feeling happy with all of this again so I don't think we need to explore alternatives for now. I'd recommend we close this unless anyone objects.
