### ISSUE TITLE
rename the repository to rdataretriever

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rdataretriever#94]
After everyone's amazing work getting the package updated and renamed I think it is now time to rename the repository to `rdataretriever`. Before I do so I just wanted to make sure everyone is good with this - noting that you will have to update your local git urls.

**Comment by ethanwhite** [comment]
:+1:

**Comment by dmcglinn** [comment]
cool I'll do this now.

**Comment by henrykironde** [comment]
@dmcglinn are you also changing the dataset and all related information to match the current retriever scripts names?

**Comment by henrykironde** [comment]
Otherwise I could put in a PR after your changes

**Comment by dmcglinn** [comment]
@henrykironde I didn't even know that that was something that needs to be done so if you can implement that would be great.
