### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#98]
I think we've ready to release at this point and it would be good to get this wending it's way through CRAN. I've rather save the announcement for a big push next week, but unless there's a reason to wait I'd say we should bump to 1.0, release, and contact CRAN about what to do about renaming.

**Comment by ethanwhite** [comment]
Thoughts @dmcglinn & @henrykironde?

We should also decide who is going to handle CRAN submissions from now on. @dmcglinn - what's your preference?

**Comment by henrykironde** [comment]
Yes I think what is left is testing and verifying if we are running smoothly.

**Comment by dmcglinn** [comment]
I'm happy to submit to CRAN because I'm already familiar with the process. We will need to update the NEWS.md file. I'll put in a PR right now that lists the changes I see and you guys can help me fill in the rest.

**Comment by ethanwhite** [comment]
:+1: 

We also need to bump the version and I see no reason not to go to 1.0 at this point.
